name: Deploy Mainnet API

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set production stage
        run: |
          mkdir -p .sst
          echo production > .sst/stage

      - name: Deploy stack
        run: yarn deploy
        with:
          NETWORK: mumbai
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          # TODO
          TOKEN_ADDRESS: 0x74909542f6Aa557eC1ef30e633F3d027e18888E2
          FARM_ADDRESS: 0x7f6279D037587d647b529F1C6ACA43E4E314d392
          INVENTORY_ADDRESS: 0x28f123423a76443D45e4BA96A512ffd42759BBCb
          SFF_TOKEN_ADDRESS: 0xdf9B4b57865B403e08c85568442f95c26b7896b0
          SFF_FARM_ADDRESS: 0x6e5Fa679211d7F6b54e14E187D34bA547c5d3fe0
